import type { Metadata } from "next";
import { Shippori_Mincho } from "next/font/google";
import { Noto_Serif_JP } from "next/font/google";
import "./globals.css";


const inter = Shippori_Mincho({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Splitter</title>
      </head>
      <body className={inter.className + " bg-gray-300 opacity-100"}>{children}</body>
    </html>
  );
}
